services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3005:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:secret@postgres:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3005"
      PGRST_JWT_SECRET: "<your_keys>"
      PGRST_JWT_ROLE_CLAIM_KEY: ".resource_access.nextjs.roles[0]"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: keycloak
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: app_user
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: adminpassword
      KC_HTTP_ENABLED: true
      KEYCLOAK_SSL_REQUIRED: none
    depends_on:
      - postgres
    command: start
volumes:
  db-data:
