@baseUrl=http://localhost:3005/todolist

@keycloak=http://localhost:8080

@accessToken=<accessToken>

@adminAccessToken=<adminAccessToken>

@kc_client_secret=<kc_client_secret>

### Get all todos
GET {{baseUrl}}
Authorization: Bearer {{accessToken}}

### Get todo by id
GET {{baseUrl}}?id=eq.1
Authorization: Bearer {{accessToken}}

### Create todo 
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "task":"eat"
} 

### Update todo by id
PATCH {{baseUrl}}?id=eq.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "task": "prep for ramen"
}

### Delete todo by id
DELETE {{baseUrl}}?id=eq.2
Authorization: Bearer {{accessToken}} 
 
### Get admin access_token 
POST {{keycloak}}/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin-cli&username=admin&password=adminpassword&grant_type=password

##### Get access_token
POST {{keycloak}}/realms/demo/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nextjs&username=matthew&password=matthew&grant_type=password&client_secret={{kc_client_secret}}

### Get count of all users
GET {{keycloak}}/admin/realms/demo/users/count
Authorization: Bearer {{adminAccessToken}}

### Get user where username is matthew
GET {{keycloak}}/admin/realms/demo/users?username=matthew
Authorization: Bearer {{adminAccessToken}}

### Validate access token
POST {{keycloak}}/realms/demo/protocol/openid-connect/token/introspect
Content-Type: application/x-www-form-urlencoded

client_id=nextjs&client_secret={{kc_client_secret}}&token={{accessToken}}